### ISSUE TITLE
Odd entries in result data

### ISSUE THREAD

**Issue by AltynayKadyrova** [khaivngo/QuickEval#125]
There are strange entries in extracted excel file for one observer as below: 
![image](https://user-images.githubusercontent.com/42893908/100225706-ead0aa00-2f1e-11eb-909b-d91a09c80d24.png)

Also, for another observer: 
<img width="247" alt="exp7_deleted_inBook1" src="https://user-images.githubusercontent.com/42893908/100225957-4b5fe700-2f1f-11eb-9281-7a20dfbfbbf0.png">

**Comment by disastersystem** [comment]
I'm not sure I see what's strange. Could you specify a bit?

**Comment by mariuspedersen** [comment]
The observers should see image 06_X.png 15 times, but in the middle of the set there are suddenly two pairs shown with image 10_X.png, then it goes back to image 06.

**Comment by mariuspedersen** [comment]
For the second case, it seems like the observer spent a very long time to decide (3348 seconds), not sure if this was the case for the first one. @AltynayKadyrova: maybe you can check this? How long time observer 86 spent on the pair.

**Comment by disastersystem** [comment]
I see. The first case is certainly odd. I can see from the database that the user account was created before the bug was fixed, it could be that the old version was still cached in their browser when they did the experiment again. Although it does seem unlikely since it looks like the odd data is in the middle of the experiment.

In the second case. I've done experiments in he past where I've taken a 30 minute YouTube break in the middle of a experiment. So it's not unlikely the observer went and did something else before returning. Unless this was taken in a lab setting.

Two notes:
- In the first case both odd entries has the same 13 second response time, and in the second case the two first entries start with the same 20 second response time. This could be a coincidence, just something that does not seem totally random.
- I did a test yesterday and the correct selected images is shown in the exported file. So the data should not be wrong.

**Comment by AltynayKadyrova** [comment]
In 2nd case, entries should be 15 times either for image 15 or image 10. But there was 5 times 15th image and started 10 times 10th images. That was strange as we expect to get 15 entries for one image.

**Comment by AltynayKadyrova** [comment]
For example, here I found for observer id = 184, there are only 10 entries out of 15 for image 4.

<img width="272" alt="exp8_deleted_inBook1" src="https://user-images.githubusercontent.com/42893908/100370822-2ba3ee00-3007-11eb-8e74-a4b3db967a2b.png">
