### ISSUE TITLE
Counter for experiment

### ISSUE THREAD

**Issue by mariuspedersen** [khaivngo/QuickEval#126]
In this experiment there are 110 images, but the counter on the top says 111. Not a big problem/bug, but it is not accurate. 
![Skjermbilde 2020-12-18 204605](https://user-images.githubusercontent.com/10753554/102655326-6c100b00-4172-11eb-82b0-b1e783107334.png)

**Comment by AltynayKadyrova** [comment]
The same issue: 
![labels_github](https://user-images.githubusercontent.com/42893908/102798133-f6de4900-43b0-11eb-84f1-f57851272428.JPG)

**Comment by mariuspedersen** [comment]
In the last one there different image sets, so it seems it is not "summing" the total number of images (which I think here should be 15 times 6)

**Comment by AltynayKadyrova** [comment]
Yes, it should be 90 but in our experiments done previously it was written 92. And Today it is 515151...

**Comment by disastersystem** [comment]
The first time the counter was considering the instructions popups as a step, that was why it was off by one or two. I was aware of it but decided not to update while experiments where ongoing.

@mariuspedersen  You're right, now it's just adding the numbers after each other in a string.
The more detailed explanation is that the database is returning strings instead og integers which it did not do before. Because I updated the website with a new version of the backend framework and this version needed a newer version of PHP. And this version is not converting strings to integers because a required PHP extension is not working correctly on the server. So I had to painfully do all the converting manually, but missed the counter part. (and it's not displaying image set names when editing a experiment either)

I'll fix it tomorrow.
