### ISSUE TITLE
Randomised order across the whole experiment

### ISSUE THREAD

**Issue by gregoryhigh** [khaivngo/QuickEval#146]
Feature Request!

Hi,

Currently it is possible to randomise the presentation of images within a set, and to randomise the order of those sets.

However, depending on the experiment, this can cause an obvious pattern to appear to the observer (all set 3 images, all set 1 images, all set 2 images, etc.)

Therefore, it would be great if we could randomise the entire experiment (across all image sets) .

Many thanks,

Greg

**Comment by disastersystem** [comment]
Hi Greg,

This request caught me at a busy time unfortunately, but the feature has been live for a few days now. So it's there now if you or anyone else need it in the future.

Note that this will still not randomize across instructions: If you have multiple instructions in one experiment, the randomization will only happen between instructions so that the relationship between stimuli and instructions is maintained. If randomization across instructions is needed I can do that soon.

![image](https://user-images.githubusercontent.com/19850690/146841946-dd0ad8eb-3dea-49c7-a02a-75ca6cc8b47f.png)
