### ISSUE TITLE
Cannot get back to main page

### ISSUE THREAD

**Issue by Nothing-Burger-Left-Pizza** [khaivngo/QuickEval#157]
I cannot return to the main page; it re-directs me to the list of experiments, so I cannot sign up as an experimenter.
--Steve

**Comment by mariuspedersen** [comment]
Try to open the page in incognito mode. this can be done in Chrome by pressing "CTRL+N" (should also work in other browsers on Windows) or "Command-Shift-N" on a Mac. That should bring you to the first page.

**Comment by Nothing-Burger-Left-Pizza** [comment]
Quoting mariuspedersen ***@***.***>:

> Try to open the page in incognito mode. this can be done in Chrome  
> by pressing "CTRL+N" (should also work in other browsers on Windows)  
> or "Command-Shift-N" on a Mac. That should bring you to the first  
> page.

Tak, Marius!

--Steve

**Comment by disastersystem** [comment]
Even after participating anonymously you have to sign out (top right corner icon) to not be re-directed away from the main page (login page). Using incognito mode like Marius suggested would work too. It is like that because technically you're logged in; a non-identifiable ID is created to make sure progress is not lost if the user refreshes the page during a experiment.

I realize it is kind of confusing that you have to "sign out" after participating anonymously, so I'll remove the re-direct for anonymous users. Thanks for helping out Marius.
