### ISSUE TITLE
Test images corrupted by the gray masks

### ISSUE THREAD

**Issue by ping-zhao** [khaivngo/QuickEval#35]
The test images displayed in the rank order mode were corrupted by the gray masks whenever the images were dragged to leave their initial positions. It can be very difficult for observers to determine whether the images were simply masked or the test image were distorted for experimental purpose. Alternatively, it is possible to apply colors to the labels or make them bold for example rather than corrupting the test images.

For example, this is the initial status of rank order without dragging anything.

![initial_status](https://cloud.githubusercontent.com/assets/9220129/6094846/e7b58604-af3d-11e4-8c1d-f509a65431b2.png)

After dragging a few images.

![order_changed](https://cloud.githubusercontent.com/assets/9220129/6094847/f39bdebe-af3d-11e4-8ef5-91e380e4399a.png)

**Comment by mariuspedersen** [comment]
The idea with the gray mask was to indicate for the observer that he/she had seen this image in fullscreen. Without marking them it would be difficult to know if the observer has seen one image. 

The thumbnails are already "corrupted" because they have been scaled. However, I do see the point that some might think it is part of the experimental procedure. There might be other ways to mark that they have been moved. It could be by changing the color of the label. 

A quick solution for this is to write in the instructions to the observers that the images are becoming gray once they have been moved, to indicate that they have been seen in fullscreen.

**Comment by ping-zhao** [comment]
I would strongly recommend to remove the gray masks, because we already have numbers and letters to identify image distortions. It is much easier at least for me to look at the image content to decide whether it is in the right place even it might not be moved at all since the initial state.

**Comment by mariuspedersen** [comment]
A key point here is that one should use the thumbnails to see where it should be placed, since the thumbnails have been resized and does not represent the image accurately. I still like the idea to see which one has been viewed in full size. However, we might look at other options than a gray mask for this.

**Comment by mariuspedersen** [comment]
After testing it with Ping, we decided that the rank numbers and the image letters should change place. The letter for the image should go on top of the image, and the rank number shoule be below. This is less confusing for the observer. 
also the rank number (i.e. text below) should be increased (larger font size).

**Comment by mariuspedersen** [comment]
After testing more I agree with Ping that the gray mask should be removed.

**Comment by khaivngo** [comment]
I propose substituting  the gray mask with an icon of an eye next to the initial position, here it is implemented instead of the gray mask: 
![](http://puu.sh/g9Aus/111594813b.jpg)

**Comment by mariuspedersen** [comment]
To me this looks good! Can you also look into changing the position of the letters and numbers?

**Comment by khaivngo** [comment]
It is next on the todo list.
