### ISSUE TITLE
Paired comparison on a tablet - problem

### ISSUE THREAD

**Issue by mariuspedersen** [khaivngo/QuickEval#40]
Trying quickeval on my android tablet i am not able to select an image, i can only pan.

**Comment by khaivngo** [comment]
This happens because jQuery Panzoom stops event propagation for everything except for itself in order to allow itself to perform panning etc.
As of now selection is possible by clicking inside the zoom/magnify-bubble which comes up on android when clicking the "open new image into new tab"-icon in upper right. The best solution would be using a button on top of each reproduction when on mobile device or you have another suggestion @mariuspedersen ?

**Comment by mariuspedersen** [comment]
Could a solution be to put a check box underneath the image instead?

**Comment by disastersystem** [comment]
Image can be selected by both clicking on it or on a checkbox underneath now. 0897069eaf13f3b5903822ece83efe11841eb84d
