### ISSUE TITLE
Missing subjective rating in final report

### ISSUE THREAD

**Issue by ping-zhao** [khaivngo/QuickEval#55]
In the experiment, I have 10 groups of images, each group has 7 distortion levels, but the final report displays only 6 levels of subjective ratings for some groups. I version I used was the version "123a56deb9ec43e06728dbb7195dfaafa0c5b475" in the development branch. This is critical and it stops me from inviting more human observers.

![untitled](https://cloud.githubusercontent.com/assets/9220129/6277904/cfa36974-b892-11e4-963f-65e8f9d4573b.png)

**Comment by mariuspedersen** [comment]
How does the data look on the results page? Could you take a screen shot of that one? 

Could you also check to see if the data is stored correctly in the database?

**Comment by mariuspedersen** [comment]
On the results page the results are also missing. We have looked into the database, but it is quite difficult for us to be able to recover the data (as we are not familiar with the structure of the database).

**Comment by ping-zhao** [comment]
I did a little tracking on the problem. The missing subjective data are corresponding to the missing image mapping in the DB table "picture". For example, for image group 2, the image mapping for level 7 is missing, then the final report has no such data. For image group 6, the image mapping for level 4 is missing, however the final report assumes that everything is ordered, so it still suggests the subjective data for level 7 is missing. In a preliminary conclusion, for some reason, some code surprisingly modified the table "picture". I am pretty sure that the images were uploaded correctly before we formally started the experiment, and the numbers of images recorded in the table "pictureset" are now all correct (8 in total for each group). I did check the uploading folder, the images there are all complete and correct. Perhaps, only 6 image distortions were actually shown to the observers, but we did not notice that during the experiments. That might help to give some hints on tracking bugs, and I will try to track more perhaps later.

**Comment by mariuspedersen** [comment]
I tried to re-create Ping's problem. There is something strange. The exported CSV file looks fine with one observer (at least for me), but when I did the experiment once more the CSV file looks strange. Instead of reporting 2 observers for the first imageset, it reports four and the numbers are "strange". The ranking should be 1-7. But instead it reports "3,3,5,5,2,2,7". 
![csv](https://cloud.githubusercontent.com/assets/10753554/6307671/f1a3e44e-b93d-11e4-8eb3-c9f9b9ac6ffd.png)

**Comment by ping-zhao** [comment]
I did remove all images and upload them again, after that I logined anonymously to do the experiment twice. The results seemed to be correct. So I think this issue is related to the uploading phase, because in a few cases only 7 images are inserted into the database rather than actual 8 images. I have deployed the php runtime on a local IIS server, and this uploading issue happens several times. I put the test images here, in the case someone may want to have a quick test:

http://1drv.ms/1EIX6Cy

**Comment by mariuspedersen** [comment]
This is good to hear. However, I still think that there is an issue when the same logged in observer does the experiment twice.

**Comment by mariuspedersen** [comment]
I can verify that this is only an issue when the same logged in observer does the experiment. Using only anonymous observers the report looks ok. I'm still to verify the z-score calculations.

**Comment by mariuspedersen** [comment]
I have checked the z-score calculations for paired comparison, and the calculations are correct. However, the raw data shown on the results page (at least in test I did) one observer more than what the calculations are based on. If the raw data says 5 observers, then the z-score calculations are based on 4. It seems like something happens when the frequency matrix is obtained, but I have not debugged that yet.

**Comment by khaivngo** [comment]
> I have checked the z-score calculations for paired comparison, and the calculations are correct. However, the raw data shown on the results page (at least in test I did) one observer more than what the calculations are based on. If the raw data says 5 observers, then the z-score calculations are based on 4. It seems like something happens when the frequency matrix is obtained, but I have not debugged that yet.

That is good news, keep us updated.

**Comment by mariuspedersen** [comment]
After looking through all the code, and trying to figure out what the problem is, I have been able to narrow it down to what I thought was the reason earlier. If the same observer does the experiment several times, only of the times is counted (the same applies to an anonymous user since they get an id, and if the id is the same (i.e not logging out)) then the results will not be counted. I do not know how to solve this issue (but in the raw data table, the results are shown when the same observer has done the experiment twice). Hopefully, @khaivngo or @jehans can look at the code and perhaps understand why. 

The good thing is that the z-score calculation and storing of the data for paired comparison is 100% correct.

**Comment by mariuspedersen** [comment]
I can also confirm that the rank order z-score calculation is correct.

**Comment by mariuspedersen** [comment]
Z-scores for category judgement are now correct.
