### ISSUE TITLE
Export experiment does not work

### ISSUE THREAD

**Issue by mariuspedersen** [khaivngo/QuickEval#96]
The export experiment function does not work (http://www.ansatt.hig.no/mariusp/quick/). I also tried it on a local implementation using wamp.

**Comment by khaivngo** [comment]
Seems to work fine here. Could you specify browser and browser version?

**Comment by mariuspedersen** [comment]
Both on colourlab.no (running an earlier version of quickeval) and a local version (running the latest version). Locally I'm running Chrome (Versjon 53.0.2785.143 m), wampserver 3.0.6 (Apache 2.4.23 - PHP 5.6.25 - MySQL 5.7.14). The browser just displays a window (without any information). 

@khaivngo Do you have an account on Colourlab.no that you can test with?

**Comment by jehans** [comment]
I can further explore this if the problem avails, as I coded this bit.

**Comment by mariuspedersen** [comment]
Thanks. I appreciate it. The first would be to check if it occurs for others than just me and one of the students who made me aware of it. This is not a critical "bug", there are other issues that are more important. Any help is appreciated.

**Comment by khaivngo** [comment]
@mariuspedersen It was tested using an account on the colorlab and as was able to export just fine.

**Comment by mariuspedersen** [comment]
I only get an error when I try to export the experiment. 

(PS: this is expert experiment. Export results work fine)

**Comment by khaivngo** [comment]
That clarifies a bit, I've been testing the export of results. @jehans what is your progress on debugging it?

**Comment by jehans** [comment]
I haven't tested this live on the server yet, but Im guessing the problems are related to file and directory permissions. Eg. the same problems that were had earlier with photo uploading for experiments. 

This functionality works by creating a zip file in a folder containing the experiment details, and im guessing the error comes due to not being able to create this zip file. 

I believe the path to the folder is /ajax/scientist/data/, and the command "chmod -R 755 ./data" should be run when standing in the /ajax/scientist directory.
